language: go
sudo: false

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

matrix:
  fast_finish: true
  include:
  - go: 1.11.x
    env: GO111MODULE=on
  - go: 1.12.x
    env: GO111MODULE=on



notifications:
  email: false
